quarkus.http.ssl.certificate.key-store-file=server-keystore.jks
quarkus.http.ssl.certificate.key-store-password=secret

// Notes that may or may not be true
// quarkus.security.security-provider-config.SunPKCS11=pkcs11.cfg
// quarkus.security.security-providers=SunPKCS11
// quarkus.http.ssl.certificate.key-store-provider=SunPKCS11
// quarkus.http.ssl.certificate.key-store-keyAlias=myAlias