quarkus.http.ssl.certificate.key-store-file=null


quarkus.security.security-providers=SunPKCS11
quarkus.security.security-provider-config.SunPKCS11=/pkcs11.cfg

# KEYSTORE
quarkus.http.ssl.certificate.key-store-alias=rsaGenesis
quarkus.http.ssl.certificate.key-store-password=123456789

quarkus.http.insecure-requests=disabled

quarkus.native.additional-build-args=-H:IncludeResources=.*\\.jks

