quarkus.http.ssl.certificate.key-store-file=null
quarkus.http.ssl.certificate.key-store-password-key=keystore-password
quarkus.http.ssl.certificate.key-store-password=secret

quarkus.http.ssl.certificate.trust-store-file=server-truststore.jks
quarkus.http.ssl.certificate.trust-store-password-key=truststore-password
quarkus.http.ssl.certificate.trust-store-password=password

quarkus.security.security-providers=SunPKCS11
quarkus.security.security-provider-config.SunPKCS11=pkcs11.cfg

#quarkus.http.ssl.certificate.key-store-provider=SunPKCS11

quarkus.native.additional-build-args=-H:IncludeResources=.*\\.jks

# Notes that may or may not be true
# quarkus.security.security-providers=SunPKCS11
# quarkus.http.ssl.certificate.key-store-provider=SunPKCS11
# quarkus.http.ssl.certificate.key-store-keyAlias=myAlias